DROP TYPE IF EXISTS "ParentRequestType" CASCADE;
DROP TYPE IF EXISTS "ParentRequestStatus" CASCADE;
DROP TYPE IF EXISTS "BmiCategory" CASCADE;
DROP TYPE IF EXISTS "InvoiceStatus" CASCADE;
DROP TYPE IF EXISTS "ReductionType" CASCADE;
DROP TYPE IF EXISTS "BillingCycle" CASCADE;
DROP TYPE IF EXISTS "AttendanceStatus" CASCADE;
DROP TYPE IF EXISTS "AttendanceMethod" CASCADE;
