packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@prisma/client': false
  '@prisma/engines': false
  '@swc/core': set this to true or false
  esbuild: false
  prisma: false
  unrs-resolver: false
