packages:
  - "apps/*"
  - "packages/*"

strictDepBuilds: false

allowBuilds:
  "@parcel/watcher": true
  "@prisma/client": true
  "@prisma/engines": true
  "@swc/core": true
  "esbuild": true
  "prisma": true
  "unrs-resolver": true
